modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/advanced-shulkerboxes/issues"
[[mods]]
modId = "shulkerbox"
version = "${mod_version}"
displayName = "Advanced Shulkerboxes"
updateJSONURL = "https://update.maxhenkel.de/neoforge/shulkerbox"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/advanced-shulkerboxes"
logoFile = "icon.png"
authors = "Max Henkel"
description = '''Open Shulker Boxes in your hand'''
[[dependencies.shulkerbox]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.shulkerbox]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"